[tool.poetry]
name = "cross-catalog-search"
version = "0.1.0"
description = "An application for searching across multiple geospatial metadata catalogs."
authors = ["Henry Rodman <henry@developmentseed.org>"]
packages = [
    { include = "app" },
    # Add other packages if needed
]

[tool.poetry.dependencies]
python = "^3.9"
pystac-client = "^0.8.2"
stac-fastapi-types = "^3.0.0a1"
fastapi = "^0.111.0"
uvicorn = "^0.30.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.4.0"
pytest = "^7.4.2"
jupyterlab = "^4.2.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
