[tool.poetry]
name = "cross-catalog-search"
version = "0.1.0"
description = "An application for searching across multiple geospatial metadata catalogs."
authors = ["Henry Rodman <henry@developmentseed.org>"]
packages = [
    { include = "app" },
    # Add other packages if needed
]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.111.0"
pystac-client = "^0.8.2"
stac-fastapi-types = "^3.0.0a1"
uvicorn = "^0.30.1"
requests-mock = "^1.12.1"
pydantic-settings = "^2.3.4"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.2.3"
pre-commit = "^3.4.0"
pytest = "^7.4.2"
pytest-mock = "^3.14.0"

[tool.isort]
profile = "black"

[tool.mypy]
explicit_package_bases = true
namespace_packages = true
show_error_codes = true
strict = true
mypy_path = "src"

[tool.ruff]
select = ["E", "F", "I"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
