name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Configure Poetry to find pyproject.toml
      run: poetry config virtualenvs.path src/server/.venv

    - name: Install dependencies including dev dependencies
      working-directory: src/server
      run: poetry install --with dev

    - name: Run Tests
      working-directory: src/server
      run: poetry run pytest
